version: '2'

volumes:
  logs:
  postgres-data:

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/code
      - logs:/code/logs
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env-local
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env-local
