# Generated by Django 4.1.2 on 2022-10-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_name',
            new_name='name',
        ),
    ]
